/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `notification_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `notification_messages` (`message`) VALUES
('Accumulo paper'),
('Lavoro in Vodafone'),
('Lavoro in Fastweb'),
('Lavoro in Tre'),
('Lavoro in telecom'),
('Mi hanno bustato'),
('Ho un macchinone ma non me lo posso permettere'),
('ROTFL'),
('Sono paranoico'),
('Uso Tor'),
('Uso Emule'),
('Uso Bittorrent'),
('Cifro tutto'),
('Ho il cappello bianco'),
('Ho il cappello nero'),
('Ho il cappello grigio'),
('Ho un sacco di cappelli'),
('Sono elite perché uso Linux'),
('Uso Windows'),
('Uso OS X'),
('Leggo BackTrack'),
('Facciamo una conference call'),
('Facciamo un meeting'),
('Ti vendo la consulenza'),
('Faccio il PT'),
('Scrivo fuffa'),
('Scrivo un report'),
('Invento un report'),
('Copio-incollo'),
('Faccio l\'assessment'),
('In quattro ore mi sparo una DMZ'),
('Non faccio un cazzo dalla mattina alla sera'),
('Pranzo con i ticket restaurant, facciamo anche con due'),
('Andiamo al giappo'),
('Vado alla mensa'),
('Vado al DEFCON'),
('Vado al CCC'),
('Odio Milano ma ci vivo'),
('Lavoro nell\'IT Security'),
('Italia, pizza, pasta, mandolino, ARP spoofing'),
('Sto tutto il giorno su YouTube'),
('Vado ad Infosecurity'),
('Ho amici CC'),
('Ho amici GdF'),
('Ho amici potenti'),
('Nessuno è mai stato licenziato per aver comprato Microsoft'),
('Lavoro al PT'),
('Nessuno è mai stato licenziato per aver comprato Intel'),
('Faccio full disclosure'),
('Sono contro la full disclosure'),
('Faccio l\'ethical hacker'),
('Faccio ricerca'),
('Scrivo gli exploit'),
('Vendo gli 0day'),
('Compro gli 0day'),
('Faccio l\'aperitivo'),
('Bevo un Negroni'),
('Il mio lavoro è fuffa'),
('Mia madre non ha ancora capito che lavoro faccio');

CREATE TABLE `notification_times` (
  `chat_id` bigint(20) NOT NULL,
  `hour` tinyint(2) NOT NULL,
  PRIMARY KEY (`chat_id`,`hour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;